###########################################################################
#                               Snakefile                                 #
#                         MSc. Matheus Cosentino                          #
###########################################################################
#   ______     ___   ____    ____  __    ______   ______   .______        #
#  /      |   /   \  \   \  /   / |  |  /      | /  __  \  |   _  \       #
# |  ,----'  /  ^  \  \   \/   /  |  | |  ,----'|  |  |  | |  |_)  |      #
# |  |      /  /_\  \  \      /   |  | |  |     |  |  |  | |      /       #
# |  `----./  _____  \  \    /    |  | |  `----.|  `--'  | |  |\  \----.  #
#  \______/__/     \__\  \__/     |__|  \______| \______/  | _| `._____|  #
#                                                                         #
###########################################################################
 
##################################
# --- 1. Load Configuration --- #
#################################
configfile: "config/config.yaml"

##############################################
# --- 2. Define Conda Environment Paths --- #
#############################################  
BASTA = workflow.source_path(config["envs"]["basta"])
BLAST = workflow.source_path(config["envs"]["blast"])
CAVICOR = workflow.source_path(config["envs"]["cavicor"])
CHOPPER = workflow.source_path(config["envs"]["chopper"])
MINIMAP2 = workflow.source_path(config["envs"]["minimap2"])
R_RAREFACTION = workflow.source_path(config["envs"]["r_rarefaction"])
SAMTOOLS = workflow.source_path(config["envs"]["samtools"])
VSEARCH = workflow.source_path(config["envs"]["vsearch"])

#######################################################
# --- 3. Define workflown directory and Variables --- #
#######################################################
DATA = config["data_dir"]
OUT_DIR = config["output_dir"]

# Global Variables
SAMPLES, = glob_wildcards(DATA, "{sample}.fastq.gz")


###########################################
# --- 4. Import functions to be used --- #
##########################################
import os
import ast 
from glob import glob
from scripts.functions import get_final_outputs

############################################
# --- 5. Export functions to be used.  --- #
###########################################
import scripts.functions as functions
functions.DATA = DATA
functions.SAMPLE = SAMPLE
functions.OUT_DIR = OUT_DIR
functions.MODULES = config["modules"]
functions.get_final_outputs = get_final_outputs


#######################################
# --- 6. Load the Workflow Rules --- #
######################################
include: "rules/blast.smk"


######################################
# --- 7. Obtain the final target --- #
######################################
rule all:
  input:
    get_final_outputs() 
  onsuccess:
    print("Workflow finished successfully!")
  onerror:
    print("Workflow failed. Temporary files were NOT removed to aid debugging.")