###########################################################################
#                               Snakefile                                 #
#                         MSc. Matheus Cosentino                          #
###########################################################################
#   ______     ___   ____    ____  __    ______   ______   .______        #
#  /      |   /   \  \   \  /   / |  |  /      | /  __  \  |   _  \       #
# |  ,----'  /  ^  \  \   \/   /  |  | |  ,----'|  |  |  | |  |_)  |      #
# |  |      /  /_\  \  \      /   |  | |  |     |  |  |  | |      /       #
# |  `----./  _____  \  \    /    |  | |  `----.|  `--'  | |  |\  \----.  #
#  \______/__/     \__\  \__/     |__|  \______| \______/  | _| `._____|  #
#                                                                         #
###########################################################################
 
##################################
# --- 1. Load Configuration --- #
#################################
configfile: "config/config.yaml"

import os
from scripts.functions import get_final_outputs
import scripts.functions as functions

DATA = config["data_dir"]
OUT_DIR = config["output_dir"]

SAMPLES_OBJ = glob_wildcards(os.path.join(DATA, "{sample}.fastq.gz"))
SAMPLE = SAMPLES_OBJ.sample

# Verifica se encontrou amostras (bom para debug)
if not SAMPLE:
    print(f"WARNING: Nenhuma amostra encontrada em {DATA} com extensão .fastq.gz")

############################################
# --- 5. Export functions to be used.  --- #
###########################################
functions.DATA = DATA
functions.SAMPLE = SAMPLE
functions.OUT_DIR = OUT_DIR
functions.get_final_outputs = get_final_outputs
functions.MODULES = config["modules"]
functions.BLAST_IDENTITIES = config["blast"]["perc_identity"]

#######################################################
# --- 3. Define workflown directory and Variables --- #
#######################################################
SAMPLES = glob_wildcards(DATA, "{sample}.fastq.gz")


##############################################
# --- 2. Define Conda Environment Paths --- #
#############################################  
BLAST = config["envs"]["blast"]
CAVICOR = config["envs"]["cavicor"]
CHOPPER = config["envs"]["chopper"]
MINIMAP2 = config["envs"]["minimap2"]
R_RAREFACTION = config["envs"]["r_rarefaction"]
SAMTOOLS = config["envs"]["samtools"]
VSEARCH = config["envs"]["vsearch"]
TAXONKIT = config["envs"]["taxonkit"]


#######################################
# --- 6. Load the Workflow Rules --- #
######################################
include: "rules/blast.smk"
include: "rules/chopper.smk"
include: "rules/vsearch.smk"

######################################
# --- 7. Obtain the final target --- #
######################################
rule all:
  input:
    get_final_outputs() 
onsuccess:
  print("Workflow finished successfully!")
onerror:
  print("Workflow failed. Temporary files were NOT removed to aid debugging.")