###########################################################################
#                               Config file                               #
#                         MSc. Matheus Cosentino                          #
###########################################################################
#   ______     ___   ____    ____  __    ______   ______   .______        #
#  /      |   /   \  \   \  /   / |  |  /      | /  __  \  |   _  \       #
# |  ,----'  /  ^  \  \   \/   /  |  | |  ,----'|  |  |  | |  |_)  |      #
# |  |      /  /_\  \  \      /   |  | |  |     |  |  |  | |      /       #
# |  `----./  _____  \  \    /    |  | |  `----.|  `--'  | |  |\  \----.  #
#  \______/__/     \__\  \__/     |__|  \______| \______/  | _| `._____|  #
#                                                                         #
###########################################################################

### Main output directory
output_dir: "results"

### Add path to directory of files of interest
data_dir: "data"

### Envs with conda yaml paths to be installed
envs:
  cavicor: "envs/cavicor.yaml"
  chopper: "envs/chopper.yaml"
  vsearch: "envs/vsearch.yaml"
  minimap2: "envs/minimap2.yaml"
  samtools: "envs/samtools.yaml"
  blast: "envs/blast.yaml"
  basta: "envs/basta.yaml"
  r_rarefaction: "envs/r_rarefaction.yaml"

### Modules of requested analysis
  12s_diversity: true #blast and basta diversity of samples
  rarefaction: true #rarefaction curve of data
  abundancy: true #compare abundancy within all run samples

### resources
#diamond db to download
blast:
  - "resources/blast/" 
#basta db taxonomy
basta:
  - "resources/basta/"
#logos
logo_dirs: 
  - "resources/logo/"



########### params
blast:
  perc_identity: 
    - 70
    - 80
    - 90
    - 95 
    - 99
  evalue:
#    - 0.01    
    - 0.001
#    - 0.00001
#    - 0.000001
#    - 0.0000001
#    - 0.00000001
  max_target_seqs:
#    - 1
#    - 5
    - 10
#    - 15
#    - 20
#    - 30
#    - 50
 
basta:
  lca_depth:
    #values between 51 and 99 BASTA returns the taxonomy that is shared by at least the given percentage of hits. 
    #- 51    #percentage of best hits 51 (minimum)
    #- 75
    - 97    
    #- 100   #BASTA reads 3 best hits for each query sequence and returns the LCA of all sequences
  best_hit: 1
  percentage: 97
