############################################################################
#                              Config File                                 #
#                          MSc. Matheus Cosentino                          #
############################################################################
#    ______     ___   ____    ____  __    ______   ______   .______        #
#   /      |   /   \  \   \  /   / |  |  /      | /  __  \  |   _  \       #
#  |  ,----'  /  ^  \  \   \/   /  |  | |  ,----'|  |  |  | |  |_)  |      #
#  |  |      /  /_\  \  \      /   |  | |  |     |  |  |  | |      /       #
#  |  `----./  _____  \  \    /    |  | |  `----.|  `--'  | |  |\  \----.  #
#   \______/__/     \__\  \__/     |__|  \______| \______/  | _| `._____|  #
#                                                                          #
############################################################################

### Main output directory
output_dir: "results"

### Add path to directory of files of interest
data_dir: "data"

### Conda environment YAML paths
envs:
  cavicor: "../envs/cavicor.yaml"
  fastp: "../envs/fastp.yaml"
  vsearch: "../envs/vsearch.yaml"
  minimap2: "../envs/minimap2.yaml"
  samtools: "../envs/samtools.yaml"
  blast: "../envs/blast.yaml"
  r_rarefaction: "../envs/r_rarefaction.yaml"
  taxonkit: "../envs/taxonkit.yaml"
  multiqc: "../envs/multiqc.yaml"

### Analysis Modules
modules:
  12s_diversity: true # BLAST and Basta diversity of samples
  quality_control: true # Data quality control
  rarefaction: false # Data rarefaction curve

### resources
# Diamond DB to download
blast:
  - "resources/blast/" 
# Logos
logo_dirs: 
  - "resources/logo/"

########### params
blast:
  perc_identity: 
    - 70
    - 80
    - 90
    #- 95 
    #- 99
  evalue:
#    - 0.01    
    #- 0.001
    - 0.00001
#    - 0.000001
#    - 0.0000001
#    - 0.00000001
  max_target_seqs:
#    - 1
#    - 5
    #- 10
#    - 15
    - 20
#    - 30
#    - 50
 

vsearch:
  identity:
    #- 0.99
    #- 0.95
    - 0.9
    #- 0.85
    #- 0.8
    #- 0.7

fastp:
  min_quality: 
    - 10
  min_length: 
    - 200
  max_length: 
    - 600